import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MotiaProvider } from "@/components/MotiaProvider";
import { Toaster } from 'react-hot-toast';
import { LayoutShell } from "@/components/LayoutShell";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700", "900"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-gray-50`}
        style={{ fontFamily: 'var(--font-inter), Inter, system-ui, sans-serif' }}
      >
        <MotiaProvider address={process.env.NEXT_PUBLIC_MOTIA_WS ?? 'ws://localhost:3000'}>
          <Toaster position="top-center" />
          <LayoutShell>
          <main>
            {children}
          </main>
          </LayoutShell>
        </MotiaProvider>
      </body>
    </html>
  );
}
