/**
 * Dutch translations for country names, keyed by ISO 2-letter country code.
 * The database stores English country names; this map is used for display only.
 */
export const countryNamesNL: Record<string, string> = {
  af: 'Afghanistan',
  al: 'Albanië',
  dz: 'Algerije',
  ad: 'Andorra',
  ao: 'Angola',
  ag: 'Antigua en Barbuda',
  ar: 'Argentinië',
  am: 'Armenië',
  au: 'Australië',
  at: 'Oostenrijk',
  az: 'Azerbeidzjan',
  bs: 'Bahama\'s',
  bh: 'Bahrein',
  bd: 'Bangladesh',
  bb: 'Barbados',
  by: 'Wit-Rusland',
  be: 'België',
  bz: 'Belize',
  bj: 'Benin',
  bt: 'Bhutan',
  bo: 'Bolivia',
  ba: 'Bosnië en Herzegovina',
  bw: 'Botswana',
  br: 'Brazilië',
  bn: 'Brunei',
  bg: 'Bulgarije',
  bf: 'Burkina Faso',
  bi: 'Burundi',
  cv: 'Kaapverdië',
  kh: 'Cambodja',
  cm: 'Kameroen',
  ca: 'Canada',
  cf: 'Centraal-Afrikaanse Republiek',
  td: 'Tsjaad',
  cl: 'Chili',
  cn: 'China',
  co: 'Colombia',
  km: 'Comoren',
  cd: 'Congo-Kinshasa',
  cg: 'Congo-Brazzaville',
  cr: 'Costa Rica',
  ci: 'Ivoorkust',
  hr: 'Kroatië',
  cu: 'Cuba',
  cy: 'Cyprus',
  cz: 'Tsjechië',
  dk: 'Denemarken',
  dj: 'Djibouti',
  dm: 'Dominica',
  do: 'Dominicaanse Republiek',
  ec: 'Ecuador',
  eg: 'Egypte',
  sv: 'El Salvador',
  gq: 'Equatoriaal-Guinea',
  er: 'Eritrea',
  ee: 'Estland',
  sz: 'Swaziland',
  et: 'Ethiopië',
  fj: 'Fiji',
  fi: 'Finland',
  fr: 'Frankrijk',
  ga: 'Gabon',
  gm: 'Gambia',
  ge: 'Georgië',
  de: 'Duitsland',
  gh: 'Ghana',
  gr: 'Griekenland',
  gd: 'Grenada',
  gt: 'Guatemala',
  gn: 'Guinee',
  gw: 'Guinee-Bissau',
  gy: 'Guyana',
  ht: 'Haïti',
  hn: 'Honduras',
  hu: 'Hongarije',
  is: 'IJsland',
  in: 'India',
  id: 'Indonesië',
  ir: 'Iran',
  iq: 'Irak',
  ie: 'Ierland',
  il: 'Israël',
  it: 'Italië',
  jm: 'Jamaica',
  jp: 'Japan',
  jo: 'Jordanië',
  kz: 'Kazachstan',
  ke: 'Kenia',
  ki: 'Kiribati',
  kp: 'Noord-Korea',
  kr: 'Zuid-Korea',
  kw: 'Koeweit',
  kg: 'Kirgizië',
  la: 'Laos',
  lv: 'Letland',
  lb: 'Libanon',
  ls: 'Lesotho',
  lr: 'Liberia',
  ly: 'Libië',
  li: 'Liechtenstein',
  lt: 'Litouwen',
  lu: 'Luxemburg',
  mg: 'Madagaskar',
  mw: 'Malawi',
  my: 'Maleisië',
  mv: 'Maldiven',
  ml: 'Mali',
  mt: 'Malta',
  mh: 'Marshalleilanden',
  mr: 'Mauritanië',
  mu: 'Mauritius',
  mx: 'Mexico',
  fm: 'Micronesië',
  md: 'Moldavië',
  mc: 'Monaco',
  mn: 'Mongolië',
  me: 'Montenegro',
  ma: 'Marokko',
  mz: 'Mozambique',
  mm: 'Myanmar',
  na: 'Namibië',
  nr: 'Nauru',
  np: 'Nepal',
  nl: 'Nederland',
  nz: 'Nieuw-Zeeland',
  ni: 'Nicaragua',
  ne: 'Niger',
  ng: 'Nigeria',
  mk: 'Noord-Macedonië',
  no: 'Noorwegen',
  om: 'Oman',
  pk: 'Pakistan',
  pw: 'Palau',
  pa: 'Panama',
  pg: 'Papoea-Nieuw-Guinea',
  py: 'Paraguay',
  pe: 'Peru',
  ph: 'Filipijnen',
  pl: 'Polen',
  pt: 'Portugal',
  qa: 'Qatar',
  ro: 'Roemenië',
  ru: 'Rusland',
  rw: 'Rwanda',
  kn: 'Saint Kitts en Nevis',
  lc: 'Saint Lucia',
  vc: 'Saint Vincent en de Grenadines',
  ws: 'Samoa',
  sm: 'San Marino',
  st: 'Sao Tomé en Principe',
  sa: 'Saoedi-Arabië',
  sn: 'Senegal',
  rs: 'Servië',
  sc: 'Seychellen',
  sl: 'Sierra Leone',
  sg: 'Singapore',
  sk: 'Slowakije',
  si: 'Slovenië',
  sb: 'Salomonseilanden',
  so: 'Somalië',
  za: 'Zuid-Afrika',
  ss: 'Zuid-Soedan',
  es: 'Spanje',
  lk: 'Sri Lanka',
  sd: 'Soedan',
  sr: 'Suriname',
  se: 'Zweden',
  ch: 'Zwitserland',
  sy: 'Syrië',
  tw: 'Taiwan',
  tj: 'Tadzjikistan',
  tz: 'Tanzania',
  th: 'Thailand',
  tl: 'Oost-Timor',
  tg: 'Togo',
  to: 'Tonga',
  tt: 'Trinidad en Tobago',
  tn: 'Tunesië',
  tr: 'Turkije',
  tm: 'Turkmenistan',
  tv: 'Tuvalu',
  ug: 'Oeganda',
  ua: 'Oekraïne',
  ae: 'Verenigde Arabische Emiraten',
  gb: 'Verenigd Koninkrijk',
  us: 'Verenigde Staten',
  uy: 'Uruguay',
  uz: 'Oezbekistan',
  vu: 'Vanuatu',
  ve: 'Venezuela',
  vn: 'Vietnam',
  ye: 'Jemen',
  zm: 'Zambia',
  zw: 'Zimbabwe',
  // Extra regio's / voetbalspecifiek
  'gb-eng': 'Engeland',
  'gb-sct': 'Schotland',
  'gb-wls': 'Wales',
  'gb-nir': 'Noord-Ierland',
  xk: 'Kosovo',
};

/**
 * Returns the Dutch display name for a country given its ISO code.
 * Falls back to the provided English name (or the code itself) when no translation is available.
 */
export function getCountryNameNL(code: string, fallback?: string): string {
  return countryNamesNL[code.toLowerCase()] ?? fallback ?? code;
}

/**
 * Returns the Dutch display name for a country given its English name,
 * using the country.json list to resolve the code first.
 * Useful for WK-2026 pages where team.name is an English country name from the database.
 */
import countriesList from '@/lib/country.json';

export function getCountryDisplayNameNL(englishName: string): string {
  const entry = countriesList.find(
    (c) => c.name.toLowerCase() === englishName.toLowerCase()
  );
  if (!entry) return englishName;
  return getCountryNameNL(entry.code, englishName);
}
